name: Build sr2019 floorplan outputs

on: 
  push:
    paths:
      - '2019/**'
      - '.github/workflows/build-sr2019.yml'
jobs:
  build-2019:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 2019/requirements.txt
    - name: Build sr2019 floorplans
      working-directory: ./2019
      run: |
        ./build.sh
    - name: Archive floorplan files
      uses: actions/upload-artifact@v3
      with:
        name: "sr2019 floorplans"
        path: 2019/output
